app/src/main/AndroidManifest.xml
app/src/main/java/com/seunome/bedrocklauncher/MainActivity.kt
app/src/main/java/com/seunome/bedrocklauncher/data/ModItem.kt
app/src/main/java/com/seunome/bedrocklauncher/data/ModRepository.kt
app/src/main/java/com/seunome/bedrocklauncher/ui/HomeFragment.kt
app/src/main/java/com/seunome/bedrocklauncher/ui/ModAdapter.kt
app/src/main/java/com/seunome/bedrocklauncher/ui/ModsFragment.kt
app/src/main/java/com/seunome/bedrocklauncher/ui/ServersFragment.kt
app/src/main/res/drawable/ic_launcher.png
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_mods.xml
app/src/main/res/layout/fragment_servers.xml
app/src/main/res/layout/item_mod.xml
app/src/main/res/menu/bottom_nav_menu.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
gradle.properties
settings.gradle.kts
.github/workflows/build-apk.yml
